// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/jewelrana/Development/Gbank/Codebase/gbank-reporting-portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import DashboardOutlined from '/Users/jewelrana/Development/Gbank/Codebase/gbank-reporting-portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import FormOutlined from '/Users/jewelrana/Development/Gbank/Codebase/gbank-reporting-portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FormOutlined';
import TableOutlined from '/Users/jewelrana/Development/Gbank/Codebase/gbank-reporting-portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TableOutlined';
import ProfileOutlined from '/Users/jewelrana/Development/Gbank/Codebase/gbank-reporting-portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import CheckCircleOutlined from '/Users/jewelrana/Development/Gbank/Codebase/gbank-reporting-portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CheckCircleOutlined';
import WarningOutlined from '/Users/jewelrana/Development/Gbank/Codebase/gbank-reporting-portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/WarningOutlined';
import UserOutlined from '/Users/jewelrana/Development/Gbank/Codebase/gbank-reporting-portal/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SmileOutlined, DashboardOutlined, FormOutlined, TableOutlined, ProfileOutlined, CheckCircleOutlined, WarningOutlined, UserOutlined };
